[workspace]
resolver = "2"
members = [
  "lmml",
  "lmml-parser",
  "lmml-cli"
]

[workspace.package]
version = "0.5.0"
authors = ["yuma14"]
repository = "https://github.com/yuma140902/lmml"
license = "MIT OR Apache-2.0"
