name: Rust Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install alsa deps
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev
    - name: Install clippy
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-review'
    - name: Run tests
      run: cargo test --verbose
